export const threeLetterWords = [
  "CAT",
  "DOG",
  "SUN",
  "RUN",
  "BIG",
  "TOP",
  "HOT",
  "POT",
  "RED",
  "BED",
  "HEN",
  "PEN",
  "PIG",
  "WIN",
  "SIT",
  "FIT",
  "MIX",
  "FIX",
  "JOY",
  "MAP",
  "TAP",
  "CAP",
  "MAT",
  "RAT",
  "BAT",
  "HAT",
  "FUN",
  "NUN",
  "MUD",
  "BUD",
  "BUG",
  "HUG",
  "RUG",
  "JUG",
  "LEG",
  "PEG",
  "FIN",
  "BIN",
  "ZIP",
  "LIP",
  "TIP",
  "JAM",
  "YAM",
];

export const processedWordList: string[] = [
  "at",
  "am",
  "an",
  "ad",
  "al",
  "sad",
  "sal",
  "sap",
  "sat",
  "sam",
  "sag",
  "rat",
  "ram",
  "rag",
  "ran",
  "rap",
  "can",
  "cap",
  "cat",
  "cab",
  "hat",
  "ham",
  "had",
  "hal",
  "nab",
  "nag",
  "nan",
  "nap",
  "nat",
  "tab",
  "tad",
  "tag",
  "tan",
  "tap",
  "fan",
  "fad",
  "fat",
  "pad",
  "pan",
  "pat",
  "pal",
  "pam",
  "bad",
  "bag",
  "bam",
  "ban",
  "bat",
  "man",
  "mat",
  "mad",
  "map",
  "van",
  "vat",
  "dab",
  "dad",
  "dam",
  "dan",
  "gab",
  "gag",
  "gal",
  "gap",
  "gas",
  "jab",
  "jam",
  "jan",
  "lab",
  "lad",
  "lag",
  "lap",
  "yam",
  "yap",
  "wag",
  "zap",
  "it",
  "if",
  "in",
  "hid",
  "him",
  "hip",
  "hit",
  "bib",
  "bid",
  "big",
  "bin",
  "bit",
  "did",
  "dig",
  "dim",
  "dip",
  "sic",
  "sid",
  "sin",
  "sip",
  "sis",
  "sit",
  "fib",
  "fig",
  "fin",
  "fit",
  "rib",
  "rid",
  "rig",
  "rim",
  "rip",
  "pig",
  "pin",
  "pit",
  "lid",
  "lip",
  "lit",
  "liz",
  "tin",
  "tip",
  "tic",
  "tim",
  "jig",
  "jim",
  "kid",
  "kit",
  "kin",
  "kim",
  "wig",
  "win",
  "wit",
  "vic",
  "vim",
  "nip",
  "zip",
  "yip",
  "us",
  "up",
  "run",
  "rub",
  "rug",
  "rut",
  "hug",
  "hut",
  "hub",
  "hum",
  "cub",
  "cup",
  "cud",
  "cut",
  "bud",
  "but",
  "bun",
  "bus",
  "bum",
  "bug",
  "sun",
  "sum",
  "sub",
  "tub",
  "tug",
  "dud",
  "dug",
  "gum",
  "gun",
  "gus",
  "gut",
  "jug",
  "jut",
  "mud",
  "mug",
  "mum",
  "nub",
  "nun",
  "nut",
  "pup",
  "pun",
  "fun",
  "lug",
  "yum",
  "ed",
  "let",
  "led",
  "leg",
  "bed",
  "beg",
  "ben",
  "bet",
  "men",
  "met",
  "mel",
  "peg",
  "pen",
  "pep",
  "pet",
  "web",
  "wet",
  "wed",
  "fed",
  "get",
  "ted",
  "ten",
  "hem",
  "hen",
  "deb",
  "den",
  "keg",
  "ken",
  "yes",
  "yet",
  "jeb",
  "jet",
  "ned",
  "net",
  "red",
  "vet",
  "yen",
  "set",
  "on",
  "nod",
  "not",
  "rob",
  "rod",
  "rot",
  "ron",
  "mob",
  "mom",
  "mop",
  "pod",
  "pop",
  "pot",
  "hop",
  "hog",
  "hot",
  "gob",
  "god",
  "got",
  "lob",
  "log",
  "lop",
  "lot",
  "doc",
  "don",
  "bob",
  "bop",
  "fog",
  "sled",
  "slab",
  "slam",
  "slap",
  "slat",
  "slid",
  "slim",
  "slip",
  "slit",
  "slob",
  "slog",
  "slop",
  "slot",
  "slug",
  "slum",
  "stab",
  "stag",
  "stan",
  "stem",
  "step",
  "stop",
  "stub",
  "stud",
  "stun",
  "span",
  "spat",
  "sped",
  "spot",
  "spin",
  "spit",
  "spun",
  "spud",
  "snag",
  "snap",
  "snub",
  "snug",
  "snip",
  "snob",
  "swim",
  "skid",
  "skim",
  "skin",
  "skip",
  "skit",
  "crab",
  "crag",
  "cram",
  "crib",
  "crop",
  "drip",
  "drop",
  "drab",
  "drag",
  "drug",
  "drum",
  "frog",
  "trim",
  "trip",
  "tram",
  "trap",
  "grab",
  "flag",
  "flat",
  "flip",
  "plan",
  "planet",
  "plus",
  "glad",
  "split",
  "twins",
  "of",
  "from",
];

export const sentences: string[] = [
  "Nan had a nap in the crib.",
  "The log had mud on it.",
  "A crab can grab.",
  "Fran did a flip.",
  "A flag can flap.",
  "The man had a big crop.",
  "A big crab sat on a wet spot.",
  "The crab ran. Did Pal stop it?",
  "Ben had a drum. Drum it, Ben!",
  "A cat sat on the mat.",
  "A dog ran after the cat.",
  "A fish swam in the sea.",
  "Stan can skip.",
  "Stan can skip up a step.",
  "Sad Sam sat.",
  "Sam had a rag.",
  "Can a rag sag?",
  "Al had a hat.",
  "Hal had a cap.",
  "Sal had a can.",
  "A rat ran at a ham.",
  "A cat ran at a rat.",
  "A cat can rap a rat.",
  "Mac had a map.",
  "Pam had a pal.",
  "Pam can tag Sam.",
  "Nat had a tan cat.",
  "The tan cat ran at a fat rat.",
  "A mad cat can nab a bad rat.",
  "Nan had a tan bag.",
  "The bag had a tan tag.",
  "The man at bat had a tan cap.",
  "Pat can fan the man at bat.",
  "Dad had a bad van.",
  "Dad had a gas can.",
  "Jan had a nap.",
  "Dan had a yam.",
  "Can Dan gab at Jan?",
  "Can a cat wag?",
  "Can a rat yap?",
  "The lad ran a lap.",
  "The man at the lab had a vat.",
  "Sis had jam. Sid had a fig.",
  "Sid bit the big fat fig.",
  "Did the big hat fit Hal?",
  "Did the big hat sag a bit?",
  "Sis can sit in the cab.",
  "The cab hit a big dip.",
  "The bad lad hid in a bin.",
  "If Sid can bat, Sid can hit it.",
  "Jim had a fat lip.",
  "The cap had a rip in it.",
  "Did the big wig fit Liz?",
  "A big pig did a jig in a pit.",
  "A big lid can fit a big pan.",
  "A lid can tip. A lid can hit a rim.",
  "Did the rat nip the cat in a rib?",
  "Did the cat yip? Did the rat zip?",
  "Vic had wit. Vic had vim. Vic can win!",
  "A bug hid in the rug.",
  "Can a bug run? Can a bug hum?",
  "Bud had a tin cup.",
  "Kim had jam in a bun.",
  "Nan can hug the cub.",
  "A man sat in a hut.",
  "The bus hit a hub in a rut.",
  "Jim cut a lip. Did Jim rub it?",
  "Sam had fun!",
  "Sam dug a pit in the mud.",
  "Sam had a dip in the tub.",
  "Jan had jam in a mug.",
  "Bud had a bug in a jug.",
  "Nat had a big tan nut.",
  "Did the pup yap?",
  "Did the pup tug at Tim?",
  "Gus can lug gas in a big can.",
  "Sis can hum, but Sid sat mum.",
  "Tim met Ed at the bus.",
  "Ben had a nap in the bed.",
  "Mel had a pet pig in a pen.",
  "Did the pig let Mel pet it?",
  "Peg let a leg dip in the tub.",
  "Peg had a wet leg.",
  "Can a bug tug at a web?",
  "Can a bug rip up a web?",
  "If the pup can sit up, the pup can beg.",
  "Did Ken get Ned wet?",
  "Did Ned get mad? Did Ned get red?",
  "A cub sat in a den.",
  "Ted can get up at ten.",
  "Ed can get in a jet at ten.",
  "Ten men can sit in a bus.",
  "Deb fed a pet pig in a pen.",
  "If Jeb can bat, Jeb can get a hit.",
  "Did Mom nod yes?",
  "Ron sat on the bed.",
  "Ron had a nap on the bed.",
  "Rob got a wet mop.",
  "Rob can mop up the mud.",
  "Jan set the lid on the pot.",
  "The lid on the pot got hot.",
  "Rod fed a big fat hog in a pig pen.",
  "Deb had on a wig, but the wig did not fit.",
  "Bob got a job.",
  "Liz had a nap on the cot.",
  "Mom got Tom a red top.",
  "Did Mom let Tom get a dog?",
  "The van hit a cab in the fog.",
  "Ben can sip pop in a pop top can.",
  "If Don can jog a lot, Don can get fit.",
  "Bob got a cut on the leg. Did Bob sob?",
  "Jim slid on a red sled.",
  "Kim slid the lid on the pot.",
  "Tim got slim, but Pat got fat.",
  "Ken let the lid slam on the bin.",
  "Did Ted slap at a bug on a leg?",
  "Did Hal slog in the mud?",
  "Did Hal slip in the mud?",
  "Did the wet mud slop on Hal?",
  "A hut sat on a slab in a lot.",
  "A big fat slug sat on a log in a bog.",
  "Stan can swim.",
  "Stan swam. Stan got wet!",
];
